### ISSUE TITLE
 Failed to create plugin instance

### ISSUE THREAD

**Issue by PepijnSenders** [magic-akari/swc_mut_cjs_exports#10]
Trying to use this plugin in nextjs and getting this error:

```
Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__set_transform_plugin_core_pkg_diagnostics": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [] })
    at Object.transformSync (/Users/psenders/Documents/GitHub/web/node_modules/next/dist/build/swc/index.js:289:33)
    at Object.transformSync (/Users/psenders/Documents/GitHub/web/node_modules/next/dist/build/swc/index.js:325:21)
    at Object.process (/Users/psenders/Documents/GitHub/web/node_modules/next/dist/build/swc/jest-transformer.js:27:36)
    at ScriptTransformer.transformSource (/Users/psenders/Documents/GitHub/web/node_modules/@jest/transform/build/ScriptTransformer.js:615:31)
    at revertHook.exts (/Users/psenders/Documents/GitHub/web/node_modules/@jest/transform/build/ScriptTransformer.js:863:18)
    at Module._compile (/Users/psenders/Documents/GitHub/web/node_modules/@jest/transform/node_modules/pirates/lib/index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader (/Users/psenders/Documents/GitHub/web/node_modules/@jest/transform/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    ```

**Comment by magic-akari** [comment]
It's seems to be a compatibility issue with next.js.

What's the `@swc/core` version it used?

**Comment by PepijnSenders** [comment]
@magic-akari latest version I think, it gets the wasm from: `@next/swc-darwin-x64@latest`

**Comment by magic-akari** [comment]
I will follow the version of `swc_core`. Compatibility can be found in this link https://swc.rs/docs/plugin/selecting-swc-core
