### ISSUE TITLE
plugin crashes after update @swc/core to 1.4.0

### ISSUE THREAD

**Issue by dardino** [magic-akari/swc_mut_cjs_exports#103]
Hi, I get this error after updating @swc/core to version 1.4.0:

```bash
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/webapp/node_modules/jest-runner/build/index.js")'

Caused by:
    0: failed to invoke `swc_mut_cjs_exports` as js transform plugin at swc_mut_cjs_exports
    1: RuntimeError: unreachable
           at __rust_start_panic (<module>[1726]:0x7b89c)
           at rust_panic (<module>[1721]:0x7b84c)
           at std::panicking::rust_panic_with_hook::h7601402c0a383194 (<module>[1720]:0x7b83e)
           at std::panicking::begin_panic_handler::{{closure}}::he405aaeb801d5772 (<module>[1709]:0x7aec3)
           at std::sys_common::backtrace::__rust_end_short_backtrace::h04fac26f88d230df (<module>[1708]:0x7adf0)
           at rust_begin_unwind (<module>[1715]:0x7b4a5)
           at core::panicking::panic_fmt::h6dad0405f48e39e2 (<module>[1784]:0x7c488)
           at core::result::unwrap_failed::h7ed8731a69ab17a3 (<module>[1814]:0x8282c)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h576ee81e50546263 (<module>[383]:0x4267e)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::hd20e8bee2c63cb9b (<module>[98]:0x13729)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h5c5c5b1e0b3cbea7 (<module>[132]:0x2313e)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h6d522b21df4cfcaa (<module>[19]:0x2a8f)
           at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::hdcb48105b95c48a3 (<module>[18]:0x1b81)
           at swc_common::plugin::serialized::PluginSerializedBytes::deserialize::h0e19d44d2707fe14 (<module>[21]:0x3124)
           at __transform_plugin_process_impl (<module>[441]:0x4ccbe)
    at Compiler.transformSync (/webapp/node_modules/@swc/core/index.js:244:29)
    at transformSync (/webapp/node_modules/@swc/core/index.js:351:21)
    at Object.process (/webapp/node_modules/@swc/jest/index.js:73:45)
    at ScriptTransformer.transformSource (/webapp/node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
    at revertHook.exts (/webapp/node_modules/@jest/transform/build/ScriptTransformer.js:776:18)
    at Module._compile (/webapp/node_modules/pirates/lib/index.js:113:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader (/webapp/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
```

my package.json:

```json
{
  "devDependencies": {
    "@swc/core": "^1.3.96",
    "@swc/jest": "^0.2.36",
    "@testing-library/jest-dom": "^6.4.1",
    "@types/jest": "^29.5.12",
    "jest": "^29.7.0",
    "swc_mut_cjs_exports": "^0.86.17",
    "ts-jest": "^29.1.1",
    "typescript": "^5.2.2",
  }
}
```

**Comment by dardino** [comment]
actually I found a workaround withtout using this plugin:

in a setupAfterEnv ts file I added this following code:

```typescript
if (Object["__definePropertyMocked__"] !== true) {
  Object["__definePropertyMocked__"] = true;
  const originalDefineProperty = Object.defineProperty;
  const mutableDefineProperty = (obj, prop, attributes) => {
    // this is to prevent the error `Cannot redefine property: prototype`; prototype can not be configurable...
    if (prop === "prototype") return originalDefineProperty(obj, prop, attributes);
    return originalDefineProperty(
        obj,
        prop,
        {
          configurable: true,
          ...attributes,
        }
    );
  }
  Object.defineProperty = mutableDefineProperty;
}
```
