### ISSUE TITLE
failed to invoke `swc_mut_cjs_exports` as js transform plugin at swc_mut_cjs_exports after upgrading to Node 22

### ISSUE THREAD

**Issue by sheam** [magic-akari/swc_mut_cjs_exports#131]
After updating from Node 16 to Node 22, I am unable to run my tests. Nothing else has changed. I have been running SWC/Jest for months prior.

I have the plugin setup like this:
```javascript
  transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc/jest',
      {
        jsc: {
          experimental: {
            plugins: [['swc_mut_cjs_exports', {}]],
          },
          transform: {
            react: {
              runtime: 'automatic',
            },
          },
        },
      },
    ],
  },
```

I have the following relevant versions installed:
```
    "@swc/core": "^1.9.3",
    "@swc/jest": "^0.2.37",
    "jest": "^29.7.0",
```
node: 22.11.0

I get the following error when running `jest`:
```
Determining test suites to run...thread '<unnamed>' panicked at C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc-8.0.0\src\plugin.rs:169:14:
failed to invoke plugin: failed to invoke plugin on 'Some("C:\\Users\\sheam\\source\\repos\\BrewNinja\\StrangeBrewWeb\\StrangeBrew.App\\config\\jest-global-setup.ts")'

Caused by:
    0: failed to invoke `swc_mut_cjs_exports` as js transform plugin at swc_mut_cjs_exports
    1: wasm plugin bytecheck failed "failed without error information; enable debug assertions and the `alloc` feature in rancor for error information"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Jest: Got error running globalSetup - C:\Users\MyName\MyApp\config\jest-global-setup.ts, reason: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("C:\\Users\\MyName\\MyApp\\config\\jest-global-setup.ts")'

Caused by:
    0: failed to invoke `swc_mut_cjs_exports` as js transform plugin at swc_mut_cjs_exports
    1: wasm plugin bytecheck failed "failed without error information; enable debug assertions and the `alloc` feature in rancor for error information"
    at Compiler.transformSync (C:\Users\MyName\MyApp\node_modules\@swc\core\index.js:249:29)
    at transformSync (C:\Users\MyName\MyApp\node_modules\@swc\core\index.js:359:21)
    at Object.process (C:\Users\MyName\MyApp\node_modules\@swc\jest\index.js:73:45)
    at ScriptTransformer.transformSource (C:\Users\MyName\MyApp\node_modules\@jest\transform\build\ScriptTransformer.js:545:31)
    at revertHook.exts (C:\Users\MyName\MyApp\node_modules\@jest\transform\build\ScriptTransformer.js:776:18)
    at Module._compile (C:\Users\MyName\MyApp\node_modules\pirates\lib\index.js:113:29)
    at node:internal/modules/cjs/loader:1689:10
    at Object.newLoader (C:\Users\MyName\MyApp\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
```

Is this a known issue with Node 22?

**Comment by magic-akari** [comment]
Please verify the version of SWC you're using; your issue aligns with the CI output https://github.com/magic-akari/swc_mut_cjs_exports/actions/runs/12166033672/job/33931358021. I'll fix it soon.

**Comment by EQuincerot** [comment]
Same issue here with the swc upgrade from 1.9.3 to 1.10.0:
> failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some(".../jest.setup.ts")'
> Caused by:
        0: failed to invoke `swc_mut_cjs_exports` as js transform plugin at swc_mut_cjs_exports
        1: wasm plugin bytecheck failed "failed without error information; enable debug assertions and the `alloc` feature in rancor for error information"

**Comment by magic-akari** [comment]
> Same issue here with the swc upgrade from 1.9.3 to 1.10.0:
> 
> > failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some(".../jest.setup.ts")'
> > Caused by:
> > 0: failed to invoke `swc_mut_cjs_exports` as js transform plugin at swc_mut_cjs_exports
> > 1: wasm plugin bytecheck failed "failed without error information; enable debug assertions and the `alloc` feature in rancor for error information"

try swc_mut_cjs_exports@8.0.1

**Comment by lukpsaxo** [comment]
Fixed it for me, I think this can be closed.
