### ISSUE TITLE
Plugin issues on Apple M1 chipset

### ISSUE THREAD

**Issue by baldwinjj** [magic-akari/swc_mut_cjs_exports#25]
Great plugin! Some developers on our team with M1 chips are experiencing issues. Is this something that could be addressed?

# Issue
```
cwd: /Users/path/to/project/
cmd: SD_DB_TESTS=1 NODE_ENV=test /Users/path/to/project/node_modules/.bin/jest --runInBand --colors --forceExit --verbose --watch --colors test/models/article.db.test.js

thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/path/to/project/dev/jest-setup-framework.js")'

Caused by:
    0: Failed to create plugin instance
    1: missing requires CPU features: "EnumSet(SSE2)"', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.245.20/src/plugin.rs:228:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 FAIL  test/models/article.db.test.js
  ● Test suite failed to run

    failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/path/to/project/dev/jest-setup-framework.js")'

    Caused by:
        0: Failed to create plugin instance
        1: missing requires CPU features: "EnumSet(SSE2)"

      at Compiler.transformSync (node_modules/@swc/core/index.js:241:29)
      at transformSync (node_modules/@swc/core/index.js:348:21)
      at Object.process (node_modules/@swc/jest/index.js:73:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:723:19)

thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/path/to/project/dev/jest-setup-framework.js")'

Caused by:
    0: Failed to create plugin instance
    1: missing requires CPU features: "EnumSet(SSE2)"', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.245.20/src/plugin.rs:228:14
```

# Details
```
    "@swc/core": "1.3.34",
    "@swc/helpers": "0.4.14",
    "jest_workaround": "0.1.14",
```

**Comment by baldwinjj** [comment]
Closing as duplicate: https://github.com/magic-akari/jest_workaround/issues/24#issue-1580216167
